from __future__ import annotations

from portfolio_selection_strategy_models import (
    PortfolioSelectionStrategyDefinition,
    StrategyFactorSpec,
)


def list_selection_strategies() -> list[PortfolioSelectionStrategyDefinition]:
    return list(_STRATEGIES)


def get_selection_strategy(strategy_id: str) -> PortfolioSelectionStrategyDefinition:
    normalized_id = strategy_id.strip()
    for strategy in _STRATEGIES:
        if strategy.strategy_id == normalized_id:
            return strategy
    raise ValueError(f"unknown portfolio selection strategy: {strategy_id}")


def _factor(
    key: str,
    label: str,
    direction: str,
    default_weight: float,
    *,
    default_lookback: int | None = None,
    lookback_candidates: list[int] | None = None,
    weight_candidates: list[float] | None = None,
    required: bool = True,
) -> StrategyFactorSpec:
    return StrategyFactorSpec(
        key=key,
        label=label,
        direction=direction,
        default_weight=default_weight,
        default_lookback=default_lookback,
        lookback_candidates=lookback_candidates or [],
        weight_candidates=weight_candidates or [],
        required=required,
    )


_STRATEGIES: tuple[PortfolioSelectionStrategyDefinition, ...] = (
    PortfolioSelectionStrategyDefinition(
        strategy_id="steady_low_vol_momentum",
        name="稳健低波动动量策略",
        description="选择中期动量向上、波动和下行波动更温和、流动性足够的股票。",
        suitable_for="偏耐心、希望收益曲线稳步抬升且不追逐剧烈波动的组合轮动。",
        caveats=[
            "强牛市中可能跑输高弹性突破策略。",
            "低波动不代表无回撤，仍需观察验证集回撤和换手。",
        ],
        default_rebalance_frequency="monthly",
        default_top_n=5,
        top_n_candidates=[2, 3, 5, 10],
        factors=[
            _factor(
                "momentum_return",
                "中期动量收益",
                "higher_better",
                0.35,
                default_lookback=60,
                lookback_candidates=[40, 60, 90, 120],
                weight_candidates=[0.2, 0.35, 0.5],
            ),
            _factor(
                "realized_volatility",
                "实现波动率",
                "lower_better",
                0.25,
                default_lookback=20,
                lookback_candidates=[10, 20, 40],
                weight_candidates=[0.15, 0.25, 0.35],
            ),
            _factor(
                "downside_volatility",
                "下行波动率",
                "lower_better",
                0.20,
                default_lookback=20,
                lookback_candidates=[10, 20, 40],
                weight_candidates=[0.1, 0.2, 0.3],
            ),
            _factor(
                "liquidity_turnover",
                "流动性成交额",
                "higher_better",
                0.10,
                default_lookback=20,
                lookback_candidates=[10, 20, 40],
                weight_candidates=[0.05, 0.1, 0.2],
            ),
            _factor(
                "ma_trend",
                "均线趋势确认",
                "higher_better",
                0.10,
                default_lookback=60,
                lookback_candidates=[40, 60, 90],
                weight_candidates=[0.05, 0.1, 0.2],
            ),
        ],
    ),
    PortfolioSelectionStrategyDefinition(
        strategy_id="strong_trend_breakout",
        name="强趋势突破策略",
        description="选择突破近期价格区间、成交量同步放大、趋势确认较强的股票。",
        suitable_for="愿意承受更高波动，捕捉趋势启动和阶段性强势行情的组合轮动。",
        caveats=[
            "突破失败时回撤可能更快，需要关注验证集回撤和高波动风险标记。",
            "成交量确认不足时不应单独依赖价格突破。",
        ],
        default_rebalance_frequency="weekly",
        default_top_n=5,
        top_n_candidates=[2, 3, 5, 10],
        factors=[
            _factor(
                "breakout_strength",
                "突破强度",
                "higher_better",
                0.35,
                default_lookback=60,
                lookback_candidates=[40, 60, 90, 120],
                weight_candidates=[0.2, 0.35, 0.5],
            ),
            _factor(
                "momentum_return",
                "中期动量收益",
                "higher_better",
                0.25,
                default_lookback=60,
                lookback_candidates=[40, 60, 90],
                weight_candidates=[0.15, 0.25, 0.4],
            ),
            _factor(
                "volume_expansion",
                "成交量放大",
                "higher_better",
                0.20,
                default_lookback=20,
                lookback_candidates=[10, 20, 40],
                weight_candidates=[0.1, 0.2, 0.3],
            ),
            _factor(
                "ma_trend",
                "均线趋势确认",
                "higher_better",
                0.15,
                default_lookback=60,
                lookback_candidates=[40, 60, 90],
                weight_candidates=[0.05, 0.15, 0.25],
            ),
            _factor(
                "realized_volatility",
                "实现波动率",
                "lower_better",
                0.05,
                default_lookback=20,
                lookback_candidates=[10, 20, 40],
                weight_candidates=[0.0, 0.05, 0.15],
            ),
        ],
    ),
    PortfolioSelectionStrategyDefinition(
        strategy_id="high_liquidity_trend",
        name="高流动性趋势策略",
        description="优先选择成交额和成交稳定性较好的趋势股票，降低流动性和执行层面的不确定性。",
        suitable_for="希望候选股票更容易跟踪、虚拟盘或手动交易更可执行的组合。",
        caveats=[
            "过度强调流动性可能错过小市值高弹性机会。",
            "仍需结合滑点、涨跌停和实际成交约束观察结果。",
        ],
        default_rebalance_frequency="monthly",
        default_top_n=5,
        top_n_candidates=[2, 3, 5, 10, 20],
        factors=[
            _factor(
                "liquidity_turnover",
                "流动性成交额",
                "higher_better",
                0.35,
                default_lookback=20,
                lookback_candidates=[10, 20, 40, 60],
                weight_candidates=[0.2, 0.35, 0.5],
            ),
            _factor(
                "volume_stability",
                "成交稳定性",
                "higher_better",
                0.20,
                default_lookback=20,
                lookback_candidates=[10, 20, 40],
                weight_candidates=[0.1, 0.2, 0.3],
            ),
            _factor(
                "ma_trend",
                "均线趋势确认",
                "higher_better",
                0.20,
                default_lookback=60,
                lookback_candidates=[40, 60, 90],
                weight_candidates=[0.1, 0.2, 0.3],
            ),
            _factor(
                "momentum_return",
                "中期动量收益",
                "higher_better",
                0.15,
                default_lookback=60,
                lookback_candidates=[40, 60, 90],
                weight_candidates=[0.05, 0.15, 0.25],
            ),
            _factor(
                "realized_volatility",
                "实现波动率",
                "lower_better",
                0.10,
                default_lookback=20,
                lookback_candidates=[10, 20, 40],
                weight_candidates=[0.0, 0.1, 0.2],
            ),
        ],
    ),
    PortfolioSelectionStrategyDefinition(
        strategy_id="drawdown_control_rotation",
        name="回撤控制型轮动策略",
        description="选择仍有动量但近期回撤、下行波动更可控，并具备一定修复能力的股票。",
        suitable_for="重视验证集最大回撤和收益曲线平滑度，宁愿慢一点也不要剧烈波动的组合。",
        caveats=[
            "强趋势初期可能因为刚经历波动而被过滤。",
            "应重点观察验证集收益曲线、回撤、换手和过拟合风险。",
        ],
        default_rebalance_frequency="monthly",
        default_top_n=5,
        top_n_candidates=[2, 3, 5, 10],
        factors=[
            _factor(
                "momentum_return",
                "中期动量收益",
                "higher_better",
                0.25,
                default_lookback=60,
                lookback_candidates=[40, 60, 90, 120],
                weight_candidates=[0.1, 0.25, 0.4],
            ),
            _factor(
                "max_drawdown_window",
                "近期最大回撤",
                "lower_better",
                0.30,
                default_lookback=60,
                lookback_candidates=[40, 60, 90, 120],
                weight_candidates=[0.15, 0.3, 0.45],
            ),
            _factor(
                "downside_volatility",
                "下行波动率",
                "lower_better",
                0.20,
                default_lookback=20,
                lookback_candidates=[10, 20, 40],
                weight_candidates=[0.1, 0.2, 0.3],
            ),
            _factor(
                "recovery_strength",
                "回撤修复强度",
                "higher_better",
                0.15,
                default_lookback=60,
                lookback_candidates=[40, 60, 90],
                weight_candidates=[0.05, 0.15, 0.25],
            ),
            _factor(
                "liquidity_turnover",
                "流动性成交额",
                "higher_better",
                0.10,
                default_lookback=20,
                lookback_candidates=[10, 20, 40],
                weight_candidates=[0.05, 0.1, 0.2],
            ),
        ],
    ),
    PortfolioSelectionStrategyDefinition(
        strategy_id="value_quality",
        name="价值质量因子策略",
        description="优先选择估值相对合理、盈利质量和成长性更好的股票，再用趋势与流动性做确认。",
        suitable_for="更接近中长期选股研究，希望把基本面质量纳入滚动调仓回测的组合。",
        caveats=[
            "基本面数据依赖免费数据源，覆盖不足时会显示 missing_fundamentals 或策略级警告。",
            "mootdx K 线不提供完整基本面，yfinance 的 A 股 fundamental coverage 也可能不稳定。",
            "低估值可能是价值陷阱，因此仍保留趋势和流动性确认。",
        ],
        default_rebalance_frequency="monthly",
        default_top_n=5,
        top_n_candidates=[2, 3, 5, 10],
        factors=[
            _factor(
                "pe_inverse",
                "市盈率倒数",
                "higher_better",
                0.20,
                weight_candidates=[0.0, 0.15, 0.25],
                required=False,
            ),
            _factor(
                "pb_inverse",
                "市净率倒数",
                "higher_better",
                0.15,
                weight_candidates=[0.0, 0.1, 0.2],
                required=False,
            ),
            _factor(
                "roe",
                "净资产收益率",
                "higher_better",
                0.25,
                weight_candidates=[0.1, 0.25, 0.4],
                required=False,
            ),
            _factor(
                "revenue_growth",
                "收入增长",
                "higher_better",
                0.10,
                weight_candidates=[0.0, 0.1, 0.2],
                required=False,
            ),
            _factor(
                "profit_growth",
                "利润增长",
                "higher_better",
                0.15,
                weight_candidates=[0.05, 0.15, 0.25],
                required=False,
            ),
            _factor(
                "ma_trend",
                "均线趋势确认",
                "higher_better",
                0.10,
                default_lookback=60,
                lookback_candidates=[40, 60, 90],
                weight_candidates=[0.05, 0.1, 0.2],
            ),
            _factor(
                "liquidity_turnover",
                "流动性成交额",
                "higher_better",
                0.05,
                default_lookback=20,
                lookback_candidates=[10, 20, 40],
                weight_candidates=[0.0, 0.05, 0.15],
            ),
        ],
    ),
    PortfolioSelectionStrategyDefinition(
        strategy_id="custom_factor_blend",
        name="自定义因子组合",
        description="沿用 Phase 3.1 的原始动量、波动、流动性、趋势权重配置。",
        suitable_for="需要手动调整原始因子参数，或保持旧版回测行为不变的场景。",
        caveats=[
            "这是兼容入口，不提供策略模板级诊断。",
            "需要用户自行理解每个原始因子的权重含义。",
        ],
        default_rebalance_frequency="monthly",
        default_top_n=2,
        top_n_candidates=[2, 3, 5, 10, 20],
        factors=[
            _factor(
                "momentum_return",
                "动量收益",
                "higher_better",
                0.45,
                default_lookback=60,
                lookback_candidates=[20, 40, 60, 90, 120],
                weight_candidates=[0.2, 0.35, 0.5, 0.65],
            ),
            _factor(
                "realized_volatility",
                "实现波动率",
                "lower_better",
                0.25,
                default_lookback=20,
                lookback_candidates=[10, 20, 40],
                weight_candidates=[0.0, 0.25, 0.5],
            ),
            _factor(
                "liquidity_turnover",
                "流动性成交额",
                "higher_better",
                0.20,
                default_lookback=20,
                lookback_candidates=[10, 20, 40],
                weight_candidates=[0.0, 0.15, 0.3],
            ),
            _factor(
                "ma_trend",
                "趋势确认",
                "higher_better",
                0.10,
                default_lookback=60,
                lookback_candidates=[40, 60, 90],
                weight_candidates=[0.0, 0.1, 0.2],
            ),
        ],
    ),
)
