from typing import Literal

from pydantic import BaseModel, Field


ParamType = Literal["int", "float", "str", "bool"]
ParamValue = int | float | str | bool


class StrategyParamMeta(BaseModel):
    name: str
    label: str
    type: ParamType
    default: ParamValue
    search_values: list[ParamValue] = Field(default_factory=list)
    min_value: float | None = None
    max_value: float | None = None
    step: float | None = None
    description: str = ""


class StrategyMeta(BaseModel):
    name: str
    label: str
    parameters: list[StrategyParamMeta] = Field(default_factory=list)


STRATEGY_METADATA: dict[str, StrategyMeta] = {
    "sma_cross": StrategyMeta(
        name="sma_cross",
        label="双均线交叉策略",
        parameters=[
            StrategyParamMeta(
                name="n1",
                label="短期均线",
                type="int",
                default=10,
                search_values=[5, 10, 15, 20],
                min_value=2,
                max_value=60,
                step=1,
                description="短周期均线窗口，数值越小越敏感。",
            ),
            StrategyParamMeta(
                name="n2",
                label="长期均线",
                type="int",
                default=30,
                search_values=[20, 30, 45, 60],
                min_value=5,
                max_value=180,
                step=1,
                description="长周期均线窗口，应大于短期均线。",
            ),
        ],
    ),
    "rsi": StrategyMeta(
        name="rsi",
        label="RSI策略",
        parameters=[
            StrategyParamMeta(
                name="rsi_period",
                label="RSI周期",
                type="int",
                default=14,
                search_values=[6, 14, 21],
                min_value=2,
                max_value=60,
                step=1,
            ),
            StrategyParamMeta(
                name="rsi_lower",
                label="买入阈值",
                type="int",
                default=30,
                search_values=[25, 30, 35],
                min_value=1,
                max_value=50,
                step=1,
            ),
            StrategyParamMeta(
                name="rsi_upper",
                label="卖出阈值",
                type="int",
                default=70,
                search_values=[60, 70, 80],
                min_value=50,
                max_value=99,
                step=1,
            ),
        ],
    ),
    "rsi_risk_control": StrategyMeta(
        name="rsi_risk_control",
        label="RSI风控策略",
        parameters=[
            StrategyParamMeta(
                name="rsi_period",
                label="RSI周期",
                type="int",
                default=14,
                search_values=[6, 14, 21],
                min_value=2,
                max_value=60,
                step=1,
            ),
            StrategyParamMeta(
                name="rsi_buy",
                label="买入阈值",
                type="int",
                default=30,
                search_values=[25, 30, 35],
                min_value=1,
                max_value=50,
                step=1,
            ),
            StrategyParamMeta(
                name="rsi_sell",
                label="卖出阈值",
                type="int",
                default=70,
                search_values=[60, 70, 80],
                min_value=50,
                max_value=99,
                step=1,
            ),
            StrategyParamMeta(
                name="trend_ma",
                label="趋势均线",
                type="int",
                default=60,
                search_values=[30, 60, 120],
                min_value=5,
                max_value=250,
                step=1,
            ),
            StrategyParamMeta(
                name="stop_loss_pct",
                label="止损比例",
                type="float",
                default=5,
                search_values=[3, 5, 8],
                min_value=0,
                max_value=30,
                step=0.5,
            ),
            StrategyParamMeta(
                name="take_profit_pct",
                label="止盈比例",
                type="float",
                default=12,
                search_values=[8, 12, 20],
                min_value=0,
                max_value=80,
                step=0.5,
            ),
            StrategyParamMeta(
                name="max_holding_bars",
                label="最大持仓周期",
                type="int",
                default=120,
                search_values=[40, 80, 120],
                min_value=1,
                max_value=500,
                step=1,
            ),
            StrategyParamMeta(
                name="position_pct",
                label="仓位比例",
                type="float",
                default=0.95,
                search_values=[0.5, 0.8, 0.95],
                min_value=0.05,
                max_value=1,
                step=0.05,
            ),
            StrategyParamMeta(
                name="cooldown_bars",
                label="冷却周期",
                type="int",
                default=3,
                search_values=[0, 3, 5],
                min_value=0,
                max_value=60,
                step=1,
            ),
        ],
    ),
    "ma_trend_risk_control": StrategyMeta(
        name="ma_trend_risk_control",
        label="均线趋势风控策略",
        parameters=[
            StrategyParamMeta(
                name="fast_ma",
                label="短期均线",
                type="int",
                default=10,
                search_values=[5, 10, 20],
                min_value=2,
                max_value=80,
                step=1,
            ),
            StrategyParamMeta(
                name="slow_ma",
                label="长期均线",
                type="int",
                default=30,
                search_values=[20, 30, 60],
                min_value=5,
                max_value=180,
                step=1,
            ),
            StrategyParamMeta(
                name="trend_ma",
                label="趋势均线",
                type="int",
                default=60,
                search_values=[60, 120, 200],
                min_value=20,
                max_value=250,
                step=1,
            ),
            StrategyParamMeta(
                name="momentum_lookback",
                label="动量窗口",
                type="int",
                default=5,
                search_values=[3, 5, 10],
                min_value=1,
                max_value=60,
                step=1,
            ),
            StrategyParamMeta(
                name="stop_loss_pct",
                label="止损比例",
                type="float",
                default=5,
                search_values=[3, 5, 8],
                min_value=0,
                max_value=30,
                step=0.5,
            ),
            StrategyParamMeta(
                name="take_profit_pct",
                label="止盈比例",
                type="float",
                default=12,
                search_values=[8, 12, 20],
                min_value=0,
                max_value=80,
                step=0.5,
            ),
            StrategyParamMeta(
                name="position_pct",
                label="仓位比例",
                type="float",
                default=0.95,
                search_values=[0.5, 0.8, 0.95],
                min_value=0.05,
                max_value=1,
                step=0.05,
            ),
        ],
    ),
    "volume_breakout_risk_control": StrategyMeta(
        name="volume_breakout_risk_control",
        label="放量突破风控策略",
        parameters=[
            StrategyParamMeta(
                name="breakout_lookback",
                label="突破窗口",
                type="int",
                default=20,
                search_values=[10, 20, 40],
                min_value=3,
                max_value=120,
                step=1,
            ),
            StrategyParamMeta(
                name="volume_lookback",
                label="均量窗口",
                type="int",
                default=10,
                search_values=[5, 10, 20],
                min_value=3,
                max_value=80,
                step=1,
            ),
            StrategyParamMeta(
                name="volume_multiplier",
                label="放量倍数",
                type="float",
                default=2.0,
                search_values=[1.5, 2.0, 3.0],
                min_value=1,
                max_value=10,
                step=0.1,
            ),
            StrategyParamMeta(
                name="stop_loss_pct",
                label="止损比例",
                type="float",
                default=5,
                search_values=[3, 5, 8],
                min_value=0,
                max_value=30,
                step=0.5,
            ),
            StrategyParamMeta(
                name="take_profit_pct",
                label="止盈比例",
                type="float",
                default=12,
                search_values=[8, 12, 20],
                min_value=0,
                max_value=80,
                step=0.5,
            ),
            StrategyParamMeta(
                name="position_pct",
                label="仓位比例",
                type="float",
                default=0.95,
                search_values=[0.5, 0.8, 0.95],
                min_value=0.05,
                max_value=1,
                step=0.05,
            ),
        ],
    ),
    "macd_volume_divergence_risk_control": StrategyMeta(
        name="macd_volume_divergence_risk_control",
        label="MACD放量背离风控策略",
        parameters=[
            StrategyParamMeta(
                name="fast_period",
                label="MACD快线周期",
                type="int",
                default=12,
                search_values=[8, 12, 16],
                min_value=2,
                max_value=60,
                step=1,
            ),
            StrategyParamMeta(
                name="slow_period",
                label="MACD慢线周期",
                type="int",
                default=26,
                search_values=[20, 26, 34],
                min_value=5,
                max_value=120,
                step=1,
            ),
            StrategyParamMeta(
                name="signal_period",
                label="DEA平滑周期",
                type="int",
                default=9,
                search_values=[6, 9, 12],
                min_value=2,
                max_value=40,
                step=1,
            ),
            StrategyParamMeta(
                name="volume_lookback",
                label="均量窗口",
                type="int",
                default=20,
                search_values=[10, 20, 30],
                min_value=3,
                max_value=120,
                step=1,
            ),
            StrategyParamMeta(
                name="volume_multiplier",
                label="放量倍数",
                type="float",
                default=2.0,
                search_values=[1.5, 2.0, 2.5],
                min_value=1,
                max_value=10,
                step=0.1,
            ),
            StrategyParamMeta(
                name="divergence_lookback",
                label="背离窗口",
                type="int",
                default=60,
                search_values=[30, 60, 90],
                min_value=10,
                max_value=180,
                step=1,
            ),
            StrategyParamMeta(
                name="zero_axis_threshold",
                label="零轴距离阈值",
                type="float",
                default=0.03,
                search_values=[0.02, 0.03, 0.05],
                min_value=0.001,
                max_value=0.2,
                step=0.001,
                description="DIF/DEA 距离零轴占收盘价的比例，越小越强调零轴附近金叉。",
            ),
            StrategyParamMeta(
                name="trend_ma",
                label="风险趋势线",
                type="int",
                default=30,
                search_values=[20, 30, 60],
                min_value=5,
                max_value=250,
                step=1,
            ),
            StrategyParamMeta(
                name="histogram_fade_bars",
                label="红柱衰减根数",
                type="int",
                default=3,
                search_values=[2, 3, 4],
                min_value=2,
                max_value=10,
                step=1,
            ),
            StrategyParamMeta(
                name="stop_loss_pct",
                label="止损比例",
                type="float",
                default=5,
                search_values=[3, 5, 8],
                min_value=0,
                max_value=30,
                step=0.5,
            ),
            StrategyParamMeta(
                name="take_profit_pct",
                label="止盈比例",
                type="float",
                default=12,
                search_values=[8, 12, 20],
                min_value=0,
                max_value=80,
                step=0.5,
            ),
            StrategyParamMeta(
                name="trailing_stop_pct",
                label="移动止盈回撤",
                type="float",
                default=6,
                search_values=[4, 6, 10],
                min_value=0,
                max_value=40,
                step=0.5,
            ),
            StrategyParamMeta(
                name="max_holding_bars",
                label="最大持仓周期",
                type="int",
                default=80,
                search_values=[40, 80, 120],
                min_value=1,
                max_value=500,
                step=1,
            ),
            StrategyParamMeta(
                name="position_pct",
                label="仓位比例",
                type="float",
                default=0.95,
                search_values=[0.5, 0.8, 0.95],
                min_value=0.05,
                max_value=1,
                step=0.05,
            ),
        ],
    ),
}


def get_strategy_metadata(strategy_name: str) -> StrategyMeta:
    return STRATEGY_METADATA.get(
        strategy_name,
        StrategyMeta(name=strategy_name, label=strategy_name, parameters=[]),
    )


def get_strategy_parameters(strategy_name: str) -> list[dict]:
    return [
        param.model_dump()
        for param in get_strategy_metadata(strategy_name).parameters
    ]
